apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: common-nodejs-parent
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: common-nodejs-parent
    app.kubernetes.io/part-of: build-nudge-example
  name: common-nodejs-parent
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: common-nodejs-parent
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: common-nodejs-parent
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/arewm-tenant/build-nudge-example/common-nodejs-parent@sha256:1052dc471b4c7608c637094ba7a4c30c71ae3d631a032b5b89b778265cb48a81
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
