apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: common-nodejs-parent
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/arewm-tenant/build-nudge-example/common-nodejs-parent@sha256:09553ce05b10cbc194dcf8f86fb8f4dae7ca275cb00b09004d6793076fcabd3d
        name: container-image
        resources: {}
status: {}
