apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: common-nodejs-parent
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/arewm-tenant/build-nudge-example/common-nodejs-parent@sha256:6c40acf3e4b24e056fcf1b3598064d0cf2468c59fc2a1e7016d236869512a5ce
        name: container-image
        resources: {}
status: {}
